name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        sudo apt-get install qemu binfmt-support qemu-user-static
        sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes 
        wget https://osdn.net/projects/manjaro-arm/storage/.rootfs/Manjaro-ARM-aarch64-latest.tar.gz

        mkdir manjaro-fs
        tar -xvf Manjaro-ARM-aarch64-latest.tar.gz -C manjaro-fs/

        cd manjaro-fs/
        echo "nameserver 8.8.8.8" > etc/resolv.conf
        cp ../Dockerfile .
        
        cp ../tigervnc/tigervnc-1.10.1-1-aarch64.pkg.tar.xz .
        cp ../tigervnc/lib.tar.xz usr/lib/a.tar.xz

        cp ../tigervnc/vncserver-start usr/local/bin/vncserver-start
        cp ../tigervnc/vncserver-stop usr/local/bin/vncserver-stop

        sudo docker build --tag manjaro-rootfs:latest .

        cd ..

        sudo docker images
        sudo docker save manjaro-rootfs > manjaro-latest.tar

        mkdir manjaro
        python.py undocker/undocker.py -i -o manjaro < manjaro-latest.tar

        cd manjaro
        rm tigervnc-1.10.1-1-aarch64.pkg.tar.xz
        rm Dockerfile
        rm setup.sh

        tar -czvf manjaro-latest.tar.gz .

        ls -la

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: v0.0.6-manjaro-anki
        artifacts: manjaro-latest.tar.gz
        token: ${{ secrets.GITHUB_TOKEN }}